/**
 * Built-in registry mapping bare names to git URLs.
 * Covers popular libraries across JS/TS, Go, Rust, and Python ecosystems.
 */
export const builtinRegistry: Record<string, string> = {
	// --- JavaScript / TypeScript ---
	react: "https://github.com/facebook/react.git",
	next: "https://github.com/vercel/next.js.git",
	vue: "https://github.com/vuejs/core.git",
	nuxt: "https://github.com/nuxt/nuxt.git",
	svelte: "https://github.com/sveltejs/svelte.git",
	angular: "https://github.com/angular/angular.git",
	solid: "https://github.com/solidjs/solid.git",
	remix: "https://github.com/remix-run/remix.git",
	astro: "https://github.com/withastro/astro.git",
	gatsby: "https://github.com/gatsbyjs/gatsby.git",
	express: "https://github.com/expressjs/express.git",
	fastify: "https://github.com/fastify/fastify.git",
	hono: "https://github.com/honojs/hono.git",
	koa: "https://github.com/koajs/koa.git",
	nest: "https://github.com/nestjs/nest.git",
	effect: "https://github.com/Effect-TS/effect.git",
	zod: "https://github.com/colinhacks/zod.git",
	valibot: "https://github.com/fabian-hiller/valibot.git",
	typescript: "https://github.com/microsoft/TypeScript.git",
	bun: "https://github.com/oven-sh/bun.git",
	deno: "https://github.com/denoland/deno.git",
	node: "https://github.com/nodejs/node.git",
	vite: "https://github.com/vitejs/vite.git",
	webpack: "https://github.com/webpack/webpack.git",
	esbuild: "https://github.com/evanw/esbuild.git",
	rollup: "https://github.com/rollup/rollup.git",
	tailwindcss: "https://github.com/tailwindlabs/tailwindcss.git",
	prisma: "https://github.com/prisma/prisma.git",
	drizzle: "https://github.com/drizzle-team/drizzle-orm.git",
	trpc: "https://github.com/trpc/trpc.git",
	tanstack: "https://github.com/TanStack/query.git",
	zustand: "https://github.com/pmndrs/zustand.git",
	jotai: "https://github.com/pmndrs/jotai.git",
	redux: "https://github.com/reduxjs/redux.git",
	playwright: "https://github.com/microsoft/playwright.git",
	vitest: "https://github.com/vitest-dev/vitest.git",
	jest: "https://github.com/jestjs/jest.git",
	storybook: "https://github.com/storybookjs/storybook.git",
	eslint: "https://github.com/eslint/eslint.git",
	prettier: "https://github.com/prettier/prettier.git",
	biome: "https://github.com/biomejs/biome.git",
	three: "https://github.com/mrdoob/three.js.git",
	d3: "https://github.com/d3/d3.git",
	electron: "https://github.com/electron/electron.git",
	tauri: "https://github.com/tauri-apps/tauri.git",
	shadcn: "https://github.com/shadcn-ui/ui.git",
	radix: "https://github.com/radix-ui/primitives.git",
	"headless-ui": "https://github.com/tailwindlabs/headlessui.git",

	// --- Go ---
	gin: "https://github.com/gin-gonic/gin.git",
	echo: "https://github.com/labstack/echo.git",
	fiber: "https://github.com/gofiber/fiber.git",
	cobra: "https://github.com/spf13/cobra.git",
	viper: "https://github.com/spf13/viper.git",
	gorm: "https://github.com/go-gorm/gorm.git",
	chi: "https://github.com/go-chi/chi.git",
	zap: "https://github.com/uber-go/zap.git",
	logrus: "https://github.com/sirupsen/logrus.git",
	testify: "https://github.com/stretchr/testify.git",
	"go-kit": "https://github.com/go-kit/kit.git",
	gorilla: "https://github.com/gorilla/mux.git",
	"grpc-go": "https://github.com/grpc/grpc-go.git",
	hugo: "https://github.com/gohugoio/hugo.git",
	terraform: "https://github.com/hashicorp/terraform.git",

	// --- Rust ---
	tokio: "https://github.com/tokio-rs/tokio.git",
	axum: "https://github.com/tokio-rs/axum.git",
	actix: "https://github.com/actix/actix-web.git",
	serde: "https://github.com/serde-rs/serde.git",
	clap: "https://github.com/clap-rs/clap.git",
	anyhow: "https://github.com/dtolnay/anyhow.git",
	thiserror: "https://github.com/dtolnay/thiserror.git",
	reqwest: "https://github.com/seanmonstar/reqwest.git",
	diesel: "https://github.com/diesel-rs/diesel.git",
	sqlx: "https://github.com/launchbadge/sqlx.git",
	bevy: "https://github.com/bevyengine/bevy.git",
	wasm: "https://github.com/aspect-build/rules_wasm.git",
	rocket: "https://github.com/rwf2/Rocket.git",

	// --- Python ---
	fastapi: "https://github.com/fastapi/fastapi.git",
	django: "https://github.com/django/django.git",
	flask: "https://github.com/pallets/flask.git",
	pytorch: "https://github.com/pytorch/pytorch.git",
	tensorflow: "https://github.com/tensorflow/tensorflow.git",
	langchain: "https://github.com/langchain-ai/langchain.git",
	pandas: "https://github.com/pandas-dev/pandas.git",
	numpy: "https://github.com/numpy/numpy.git",
	pydantic: "https://github.com/pydantic/pydantic.git",
	sqlalchemy: "https://github.com/sqlalchemy/sqlalchemy.git",
	celery: "https://github.com/celery/celery.git",
	httpx: "https://github.com/encode/httpx.git",
	scrapy: "https://github.com/scrapy/scrapy.git",
	pytest: "https://github.com/pytest-dev/pytest.git",
	ruff: "https://github.com/astral-sh/ruff.git",

	// --- AI / ML ---
	transformers: "https://github.com/huggingface/transformers.git",
	"ollama-js": "https://github.com/ollama/ollama-js.git",
	"openai-node": "https://github.com/openai/openai-node.git",
	"openai-python": "https://github.com/openai/openai-python.git",
	"anthropic-sdk": "https://github.com/anthropics/anthropic-sdk-typescript.git",
};
